### ISSUE TITLE
Error when I deloy it

### ISSUE THREAD

**Issue by 3qthanh7** [bartbutenaers/node-red-contrib-ui-svg#117]
I tried many ways like reinstalling nodes but it didn't work
<img width="232" alt="image" src="https://user-images.githubusercontent.com/102430232/217260427-c653e308-fcfd-44ba-a237-e2987adfe57e.png">
In console:
Error: Module not allowed
    at Object.requireModule [as require] (C:\Users\thanh\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\externalModules.js:104:19)
    at Object.requireModule [as require] (C:\Users\thanh\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\util.js:51:45)
    at new SvgGraphicsNode (C:\Users\thanh\node_modules\node-red-contrib-ui-svg\svg_graphics.js:273:26)
    at Object.createNode (C:\Users\thanh\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\util.js:90:27)
    at Flow.start (C:\Users\thanh\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\Flow.js:206:48)
    at start (C:\Users\thanh\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\index.js:394:33) {
  code: 'module_not_allowed'
}
7 Feb 20:24:17 - [error] [ui_svg_graphics:cdd139a16b628121] TypeError: Cannot read properties of undefined (reading 'push')
My Nodes:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/102430232/217261136-2b0862ad-e91a-4575-b511-4bb6a3b182b5.png">

**Comment by bartbutenaers** [comment]
Hi @3qthanh7,

It seems to fail on [this](https://github.com/bartbutenaers/node-red-contrib-ui-svg/blob/master/svg_graphics.js#L273) statement, i.e. it can't find the Node-RED dashboard.

Indeed when I see your screenshot I see that you haven't installed the official dashboard.  Ui nodes won't work without it.. 

Bart
